language: ruby
env:
  global:
    - secure: <encrypted_env_vars> # See AEROBATIC_API_KEY
install:
  - bundle install --path vendor/bundle
  - npm install
script:
  - bundle exec jekyll build
after_success:
  - npm install aerobatic-cli -g
  - aero deploy \
    --commit-url "https://github.com/owner/repo-name/commit/${TRAVIS_COMMIT}" \
    --deploy-dir _site