language: ruby
rvm:
- 2.3.3

install:
  - bundle install
  - npm install -g aerobatic-cli

script: jekyll build && htmlproofer ./_site

after_success:
- aero deploy -d _site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

