
# SEO settings
title: Simplest
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: https://wide-eyed-fall.aerobatic.io
baseurl: "https://wide-eyed-fall.aerobatic.io"
# baseurl: null

google_analytics: UA-52446115-1
repo: http://github.com/dundonian/simplest
disqus_shortname: "jasongowans"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Jason Gowans
  job      : Aerobatic
  bio      : "Me like work."
  thumb    : /images/author.jpg
  email    : jason@aerobatic.com
  url      : https://www.aerobatic.com
  github   : http://github.com/aerobatic
  twitter  : http://twitter.com/aerobaticapp

# social settings
og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "@aerobaticapp"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
